### ISSUE TITLE
Parameter configuration of “unary_model_trainer” module in Philipp's Model

### ISSUE THREAD

**Issue by laoyezi** [tttor/lab1231-sun-prj#65]
@tttor 
hello! In your source code "trainer.cpp", I do not know what the four parameters list_path, img_folder, png_folder, param_dir mean, how is this configured? 
I look forward to hearing from you. Thank you.

**Comment by tttor** [comment]
Hi there: Unfortunately, this repository is not maintained anymore.

**Comment by laoyezi** [comment]
Oh no! anyway, thank you for the answer.
